<a href="https://colab.research.google.com/github/priyankacoder24-code/DSA-26-27/blob/main/Salary_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Salary_Data.csv")

In [3]:
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28,Female,Master's,Data Analyst,3.0,65000.0
2,45,Male,PhD,Senior Manager,15.0,150000.0
3,36,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52,Male,Master's,Director,20.0,200000.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6702 entries, 0 to 6701
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   int64
 1   Gender               6702 non-null   object
 2   Education Level      6701 non-null   object
 3   Job Title            6702 non-null   object
 4   Years of Experience  6701 non-null   float64
 5   Salary               6699 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 314.3+ KB

In [5]:
df.describe()

               Age  Years of Experience         Salary
count  6702.000000          6701.000000    6699.000000
mean     33.620859             8.094687  115326.964771
std       7.614633             6.059003   52786.183911
min      21.000000             0.000000     350.000000
25%      28.000000             3.000000   70000.000000
50%      32.000000             7.000000  115000.000000
75%      38.000000            12.000000  160000.000000
max      62.000000            34.000000  250000.000000

In [6]:
df.isnull().sum()

Age                    0
Gender                 0
Education Level        1
Job Title              0
Years of Experience    1
Salary                 3
dtype: int64

In [7]:
df["Education Level"].unique()

array(["Bachelor's", "Master's", 'PhD', "Bachelor's Degree",
       "Master's Degree", nan, 'High School', 'phD'], dtype=object)

In [8]:
df["Education Level"] = df["Education Level"].replace("Bachelor's","Bachelor's Degree" )

In [9]:
df["Education Level"].unique()

array(["Bachelor's Degree", "Master's", 'PhD', "Master's Degree", nan,
       'High School', 'phD'], dtype=object)

In [10]:
df["Education Level"] = df["Education Level"].replace("Master's","Master's Degree" )

In [11]:
df["Education Level"].unique()

array(["Bachelor's Degree", "Master's Degree", 'PhD', nan, 'High School',
       'phD'], dtype=object)

In [12]:
df["Education Level"] = df["Education Level"].replace("phD","PhD",)

In [13]:
df["Education Level"].unique()

array(["Bachelor's Degree", "Master's Degree", 'PhD', nan, 'High School'],
      dtype=object)

In [14]:
df["Education Level"] = df["Education Level"].fillna(df["Education Level"].mode()[0])

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6702 entries, 0 to 6701
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   int64
 1   Gender               6702 non-null   object
 2   Education Level      6702 non-null   object
 3   Job Title            6702 non-null   object
 4   Years of Experience  6701 non-null   float64
 5   Salary               6699 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 314.3+ KB

In [16]:
df["Years of Experience"].skew()

np.float64(0.981187602540142)

In [17]:
df["Years of Experience"] = df["Years of Experience"].fillna(df["Years of Experience"].mean())

In [18]:
df["Salary"].skew()

np.float64(0.05734392354615517)

In [19]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6702 entries, 0 to 6701
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   int64
 1   Gender               6702 non-null   object
 2   Education Level      6702 non-null   object
 3   Job Title            6702 non-null   object
 4   Years of Experience  6702 non-null   float64
 5   Salary               6702 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 314.3+ KB

In [21]:
df = pd.get_dummies(df,columns = ["Gender"],drop_first= True) #nominal data (no herichy)

In [22]:
df.head()

,Age,Education Level,Job Title,Years of Experience,Salary,Gender_Male,Gender_Other
0,32,Bachelor's Degree,Software Engineer,5.0,90000.0,True,False
1,28,Master's Degree,Data Analyst,3.0,65000.0,False,False
2,45,PhD,Senior Manager,15.0,150000.0,True,False
3,36,Bachelor's Degree,Sales Associate,7.0,60000.0,False,False
4,52,Master's Degree,Director,20.0,200000.0,True,False

In [23]:
#ordinal Encoding
from sklearn.preprocessing import OrdinalEncoder

In [24]:
oe = OrdinalEncoder(categories= [["High School","Bachelor's Degree", "Master's Degree", "PhD", "High Schoo"]])

In [25]:
df["Education Level"] = oe.fit_transform(df[["Education Level"]]) #fit_transform fit krne ke liye help krta a transform krta hai

In [26]:
df.head()

,Age,Education Level,Job Title,Years of Experience,Salary,Gender_Male,Gender_Other
0,32,1.0,Software Engineer,5.0,90000.0,True,False
1,28,2.0,Data Analyst,3.0,65000.0,False,False
2,45,3.0,Senior Manager,15.0,150000.0,True,False
3,36,1.0,Sales Associate,7.0,60000.0,False,False
4,52,2.0,Director,20.0,200000.0,True,False

In [27]:
print(df['Job Title'].unique()) #ignore kyuki more then 127 data h

['Software Engineer' 'Data Analyst' 'Senior Manager' 'Sales Associate'
 'Director' 'Marketing Analyst' 'Product Manager' 'Sales Manager'
 'Marketing Coordinator' 'Senior Scientist' 'Software Developer'
 'HR Manager' 'Financial Analyst' 'Project Manager' 'Customer Service Rep'
 'Operations Manager' 'Marketing Manager' 'Senior Engineer'
 'Data Entry Clerk' 'Sales Director' 'Business Analyst' 'VP of Operations'
 'IT Support' 'Recruiter' 'Financial Manager' 'Social Media Specialist'
 'Software Manager' 'Junior Developer' 'Senior Consultant'
 'Product Designer' 'CEO' 'Accountant' 'Data Scientist'
 'Marketing Specialist' 'Technical Writer' 'HR Generalist'
 'Project Engineer' 'Customer Success Rep' 'Sales Executive' 'UX Designer'
 'Operations Director' 'Network Engineer' 'Administrative Assistant'
 'Strategy Consultant' 'Copywriter' 'Account Manager'
 'Director of Marketing' 'Help Desk Analyst' 'Customer Service Manager'
 'Business Intelligence Analyst' 'Event Coordinator' 'VP of Finance'
 'Graphic Designer' 'UX Researcher' 'Social Media Manager'
 'Director of Operations' 'Senior Data Scientist' 'Junior Accountant'
 'Digital Marketing Manager' 'IT Manager'
 'Customer Service Representative' 'Business Development Manager'
 'Senior Financial Analyst' 'Web Developer' 'Research Director'
 'Technical Support Specialist' 'Creative Director'
 'Senior Software Engineer' 'Human Resources Director'
 'Content Marketing Manager' 'Technical Recruiter' 'Sales Representative'
 'Chief Technology Officer' 'Junior Designer' 'Financial Advisor'
 'Junior Account Manager' 'Senior Project Manager' 'Principal Scientist'
 'Supply Chain Manager' 'Senior Marketing Manager' 'Training Specialist'
 'Research Scientist' 'Junior Software Developer'
 'Public Relations Manager' 'Operations Analyst'
 'Product Marketing Manager' 'Senior HR Manager' 'Junior Web Developer'
 'Senior Project Coordinator' 'Chief Data Officer'
 'Digital Content Producer' 'IT Support Specialist'
 'Senior Marketing Analyst' 'Customer Success Manager'
 'Senior Graphic Designer' 'Software Project Manager'
 'Supply Chain Analyst' 'Senior Business Analyst'
 'Junior Marketing Analyst' 'Office Manager' 'Principal Engineer'
 'Junior HR Generalist' 'Senior Product Manager'
 'Junior Operations Analyst' 'Senior HR Generalist'
 'Sales Operations Manager' 'Senior Software Developer'
 'Junior Web Designer' 'Senior Training Specialist'
 'Senior Research Scientist' 'Junior Sales Representative'
 'Junior Marketing Manager' 'Junior Data Analyst'
 'Senior Product Marketing Manager' 'Junior Business Analyst'
 'Senior Sales Manager' 'Junior Marketing Specialist'
 'Junior Project Manager' 'Senior Accountant' 'Director of Sales'
 'Junior Recruiter' 'Senior Business Development Manager'
 'Senior Product Designer' 'Junior Customer Support Specialist'
 'Senior IT Support Specialist' 'Junior Financial Analyst'
 'Senior Operations Manager' 'Director of Human Resources'
 'Junior Software Engineer' 'Senior Sales Representative'
 'Director of Product Management' 'Junior Copywriter'
 'Senior Marketing Coordinator' 'Senior Human Resources Manager'
 'Junior Business Development Associate' 'Senior Account Manager'
 'Senior Researcher' 'Junior HR Coordinator' 'Director of Finance'
 'Junior Marketing Coordinator' 'Junior Data Scientist'
 'Senior Operations Analyst' 'Senior Human Resources Coordinator'
 'Senior UX Designer' 'Junior Product Manager'
 'Senior Marketing Specialist' 'Senior IT Project Manager'
 'Senior Quality Assurance Analyst' 'Director of Sales and Marketing'
 'Senior Account Executive' 'Director of Business Development'
 'Junior Social Media Manager' 'Senior Human Resources Specialist'
 'Senior Data Analyst' 'Director of Human Capital'
 'Junior Advertising Coordinator' 'Junior UX Designer'
 'Senior Marketing Director' 'Senior IT Consultant'
 'Senior Financial Advisor' 'Junior Business Operations Analyst'
 'Junior Social Media Specialist' 'Senior Product Development Manager'
 'Junior Operations Manager' 'Senior Software Architect'
 'Junior Research Scientist' 'Senior Financial Manager'
 'Senior HR Specialist' 'Senior Data Engineer'
 'Junior Operations Coordinator' 'Director of HR'
 'Senior Operations Coordinator' 'Junior Financial Advisor'
 'Director of Engineering' 'Software Engineer Manager'
 'Back end Developer' 'Senior Project Engineer' 'Full Stack Engineer'
 'Front end Developer' 'Developer' 'Front End Developer'
 'Director of Data Science' 'Human Resources Coordinator'
 'Junior Sales Associate' 'Human Resources Manager'
 'Juniour HR Generalist' 'Juniour HR Coordinator'
 'Digital Marketing Specialist' 'Receptionist' 'Marketing Director'
 'Social M' 'Social Media Man' 'Delivery Driver']

In [28]:
#Feature and Target
df.describe()

               Age  Education Level  Years of Experience         Salary
count  6702.000000      6702.000000          6702.000000    6702.000000
mean     33.620859         1.619367             8.094687  115326.964771
std       7.614633         0.882096             6.058551   52774.366549
min      21.000000         0.000000             0.000000     350.000000
25%      28.000000         1.000000             3.000000   70000.000000
50%      32.000000         1.000000             7.000000  115000.000000
75%      38.000000         2.000000            12.000000  160000.000000
max      62.000000         3.000000            34.000000  250000.000000

#
decision tree and Random forest me feature scaling nhi krne ki jarurat hoti

In [29]:
X = df[["Age","Education Level","Years of Experience"]] #multiple columns lene ke liye do bracket use krte hain
y = df["Salary"]

In [30]:
# Train-Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split( X, y,test_size=0.2,random_state=42)

In [31]:
from sklearn.preprocessing import MinMaxScaler

In [32]:
scaler = MinMaxScaler()

In [33]:
X_train[["Age","Years of Experience"]] = scaler.fit_transform(X_train[["Age","Years of Experience"]]) #fit avg min and max nikalta hai

X_test[["Age","Years of Experience"]] = scaler.transform(X_test[["Age","Years of Experience"]]) #yaha transform nhi kiya kyu ki alg avg aati fit pr

In [34]:
from sklearn.linear_model import LinearRegression

In [35]:
model = LinearRegression()

In [36]:
model.fit(X_train,y_train)

LinearRegression()

In [37]:
y_prediction = model.predict(X_test)

In [38]:
print(y_prediction)

[119603.14070126 177613.8023635   77922.28858654 ... 161277.34171754
 167408.77991271  67715.04910294]

In [39]:
print(y_test)

5071    120000.0
4462    157000.0
5557     80000.0
6540     40000.0
263      40000.0
          ...
2155    185000.0
2298    180000.0
3505    140000.0
5632    170000.0
2984     55935.0
Name: Salary, Length: 1341, dtype: float64

In [40]:
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score

In [41]:
mae = mean_squared_error(y_prediction, y_test)

In [42]:
print(mae)

810907388.476432

In [43]:
mae = mean_absolute_error(y_prediction, y_test)

In [44]:
print(mae)

22145.305585243244

In [45]:
r2 = r2_score(y_prediction,y_test)

In [46]:
print(r2)

0.5908484284253008

In [47]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6702 entries, 0 to 6701
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  6702 non-null   int64
 1   Education Level      6702 non-null   float64
 2   Years of Experience  6702 non-null   float64
dtypes: float64(2), int64(1)
memory usage: 157.2 KB

user input

In [48]:
def user_input():
  exp = float(input("Enter Years of Experience:"))
  age = int(input("Enter Age:"))
  edu = float(input("Enter Education Level(0 for High School, 1 for Bachelor's Degree , 2 for Master's Degree, 3 for PhD)"))

  #create a DataFrame with user input and column name of features

  user_data = pd.DataFrame([[age,edu,exp]], columns = ["Age", "Education Level","Years of Experience"])

  #scale the data using the Trained scaler
  user_data[["Age","Years of Experience"]] = scaler.transform(user_data[["Age","Years of Experience"]])

  #Predict using the liner regression
  user_prediction = model.predict(user_data)

  #Print the prediction REsult
  print("Predicted Salary:", user_prediction[0])

In [49]:
print(user_input)

<function user_input at 0x79d9fa701d00>